---
- name: Print welcome message
  hosts: all
  gather_facts: false
  tasks:
    - name: Print annie in ansible automation platform dashboard
      ansible.builtin.debug:
        msg: "welcome to my repository"
